/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.77
 * Generated at: 2018-05-14 02:10:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 
package org.apache.jsp.dashboard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.etc.entity.Article;
import java.util.List;
import com.etc.service.impl.ArticleSerivceImpl;
import com.etc.service.ArticleSerivce;

public final class showArticles_jsp extends org.apache.jasper.runtime.HttpJspBase
		implements org.apache.jasper.runtime.JspSourceDependent {

	private static final javax.servlet.jsp.JspFactory _jspxFactory = javax.servlet.jsp.JspFactory.getDefaultFactory();

	private static java.util.Map<java.lang.String, java.lang.Long> _jspx_dependants;

	private volatile javax.el.ExpressionFactory _el_expressionfactory;
	private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

	public java.util.Map<java.lang.String, java.lang.Long> getDependants() {
		return _jspx_dependants;
	}

	public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
		if (_el_expressionfactory == null) {
			synchronized (this) {
				if (_el_expressionfactory == null) {
					_el_expressionfactory = _jspxFactory
							.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
				}
			}
		}
		return _el_expressionfactory;
	}

	public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
		if (_jsp_instancemanager == null) {
			synchronized (this) {
				if (_jsp_instancemanager == null) {
					_jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory
							.getInstanceManager(getServletConfig());
				}
			}
		}
		return _jsp_instancemanager;
	}

	public void _jspInit() {
	}

	public void _jspDestroy() {
	}

	public void _jspService(final javax.servlet.http.HttpServletRequest request,
			final javax.servlet.http.HttpServletResponse response)
			throws java.io.IOException, javax.servlet.ServletException {

		final javax.servlet.jsp.PageContext pageContext;
		javax.servlet.http.HttpSession session = null;
		final javax.servlet.ServletContext application;
		final javax.servlet.ServletConfig config;
		javax.servlet.jsp.JspWriter out = null;
		final java.lang.Object page = this;
		javax.servlet.jsp.JspWriter _jspx_out = null;
		javax.servlet.jsp.PageContext _jspx_page_context = null;

		try {
			response.setContentType("text/html; charset=UTF-8");
			pageContext = _jspxFactory.getPageContext(this, request, response, null, true, 8192, true);
			_jspx_page_context = pageContext;
			application = pageContext.getServletContext();
			config = pageContext.getServletConfig();
			session = pageContext.getSession();
			out = pageContext.getOut();
			_jspx_out = out;

			out.write("\r\n");
			out.write("\r\n");
			out.write("\r\n");
			out.write("\r\n");
			out.write("\r\n");
			out.write("<!DOCTYPE html>\r\n");
			out.write("<html lang=\"en\">\r\n");
			out.write("<head>\r\n");
			out.write("<meta charset=\"utf-8\">\r\n");
			out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
			out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
			out.write(
					"<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\r\n");
			out.write("<meta name=\"description\" content=\"\">\r\n");
			out.write("<meta name=\"author\" content=\"\">\r\n");
			out.write("<link rel=\"icon\" href=\"../../favicon.ico\">\r\n");
			out.write("\r\n");
			out.write("<title>CMS后台管理</title>\r\n");
			out.write("\r\n");
			out.write("<!-- Bootstrap core CSS -->\r\n");
			out.write("<link href=\"../dist/css/bootstrap.css\" rel=\"stylesheet\">\r\n");
			out.write("\r\n");
			out.write("<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->\r\n");
			out.write("<link href=\"../../assets/css/ie10-viewport-bug-workaround.css\"\r\n");
			out.write("\trel=\"stylesheet\">\r\n");
			out.write("\r\n");
			out.write("<!-- Custom styles for this template -->\r\n");
			out.write("<link href=\"dashboard.css\" rel=\"stylesheet\">\r\n");
			out.write("\r\n");
			out.write("<!-- Just for debugging purposes. Don't actually copy these 2 lines! -->\r\n");
			out.write(
					"<!--[if lt IE 9]><script src=\"../../assets/js/ie8-responsive-file-warning.js\"></script><![endif]-->\r\n");
			out.write("<script src=\"../../assets/js/ie-emulation-modes-warning.js\"></script>\r\n");
			out.write("\r\n");
			out.write("<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\r\n");
			out.write("<!--[if lt IE 9]>\r\n");
			out.write("      <script src=\"https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js\"></script>\r\n");
			out.write("      <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
			out.write("    <![endif]-->\r\n");
			out.write("</head>\r\n");
			out.write("\r\n");
			out.write("<body>\r\n");
			out.write("\r\n");
			out.write("\t<nav class=\"navbar navbar-inverse navbar-fixed-top\">\r\n");
			out.write("\t\t<div class=\"container-fluid\">\r\n");
			out.write("\t\t\t<div class=\"navbar-header\">\r\n");
			out.write("\t\t\t\t<button type=\"button\" class=\"navbar-toggle collapsed\"\r\n");
			out.write("\t\t\t\t\tdata-toggle=\"collapse\" data-target=\"#navbar\" aria-expanded=\"false\"\r\n");
			out.write("\t\t\t\t\taria-controls=\"navbar\">\r\n");
			out.write("\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\r\n");
			out.write("\t\t\t\t\t\tclass=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
			out.write("\t\t\t\t\t\tclass=\"icon-bar\"></span>\r\n");
			out.write("\t\t\t\t</button>\r\n");
			out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"#\">CMS系统后台管理</a>\r\n");
			out.write("\t\t\t</div>\r\n");
			out.write("\t\t\t<div id=\"navbar\" class=\"navbar-collapse collapse\">\r\n");
			out.write("\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
			out.write("\t\t\t\t\t<li><a href=\"#\">仪表�?</a></li>\r\n");
			out.write("\t\t\t\t\t<li><a href=\"#\">设置</a></li>\r\n");
			out.write("\t\t\t\t\t<li><a href=\"#\">个人信息</a></li>\r\n");
			out.write("\t\t\t\t\t<li><a href=\"#\">帮助</a></li>\r\n");
			out.write("\t\t\t\t</ul>\r\n");
			out.write("\t\t\t\t<form class=\"navbar-form navbar-right\">\r\n");
			out.write("\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"Search...\">\r\n");
			out.write("\t\t\t\t</form>\r\n");
			out.write("\t\t\t</div>\r\n");
			out.write("\t\t</div>\r\n");
			out.write("\t</nav>\r\n");
			out.write("\r\n");
			out.write("\t<div class=\"container-fluid\">\r\n");
			out.write("\t\t<div class=\"row\">\r\n");
			out.write("\t\t\t<div class=\"col-sm-3 col-md-2 sidebar\">\r\n");
			out.write("\t\t\t\t<ul class=\"nav nav-sidebar\">\r\n");
			out.write(
					"\t\t\t\t\t<li class=\"active\"><a href=\"#\">文章管理 <span class=\"sr-only\">(current)</span></a>\r\n");
			out.write("\t\t\t\t\t</li>\r\n");
			out.write("\t\t\t\t\t<li><a href=\"#\">Reports</a></li>\r\n");
			out.write("\t\t\t\t\t<li><a href=\"#\">Analytics</a></li>\r\n");
			out.write("\t\t\t\t\t<li><a href=\"#\">Export</a></li>\r\n");
			out.write("\t\t\t\t</ul>\r\n");
			out.write("\t\t\t\t<ul class=\"nav nav-sidebar\">\r\n");
			out.write("\t\t\t\t\t<li class=\"active\"><a href=\"\">用户管理</a></li>\r\n");
			out.write("\t\t\t\t\t<li><a href=\"\">Nav item again</a></li>\r\n");
			out.write("\t\t\t\t\t<li><a href=\"\">One more nav</a></li>\r\n");
			out.write("\t\t\t\t\t<li><a href=\"\">Another nav item</a></li>\r\n");
			out.write("\t\t\t\t\t<li><a href=\"\">More navigation</a></li>\r\n");
			out.write("\t\t\t\t</ul>\r\n");
			out.write("\t\t\t\t<ul class=\"nav nav-sidebar hidden\">\r\n");
			out.write("\t\t\t\t\t<li class=\"active\"><a href=\"\">Nav item again</a></li>\r\n");
			out.write("\t\t\t\t\t<li><a href=\"\">One more nav</a></li>\r\n");
			out.write("\t\t\t\t\t<li><a href=\"\">Another nav item</a></li>\r\n");
			out.write("\t\t\t\t</ul>\r\n");
			out.write("\t\t\t</div>\r\n");
			out.write("\r\n");
			out.write("\t\t\t<div class=\"col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main\">\r\n");
			out.write("\r\n");
			out.write("\t\t\t\t<h2 class=\"sub-header\">文章列表</h2>\r\n");
			out.write("\t\t\t\t<div class=\"table-responsive\">\r\n");
			out.write("\t\t\t\t\t<table class=\"table table-striped table-hover\">\r\n");
			out.write("\t\t\t\t\t\t<thead>\r\n");
			out.write("\t\t\t\t\t\t\t<tr>\r\n");
			out.write("\t\t\t\t\t\t\t\t<th>编号</th>\r\n");
			out.write("\t\t\t\t\t\t\t\t<th>标题</th>\r\n");
			out.write("\t\t\t\t\t\t\t\t<th>内容</th>\r\n");
			out.write("\t\t\t\t\t\t\t\t<th>作�??</th>\r\n");
			out.write("\t\t\t\t\t\t\t\t<th>发布时间</th>\r\n");
			out.write("\t\t\t\t\t\t\t\t<th>操作</th>\r\n");
			out.write("\t\t\t\t\t\t\t</tr>\r\n");
			out.write("\t\t\t\t\t\t</thead>\r\n");
			out.write("\t\t\t\t\t\t<tbody>\r\n");
			out.write("\r\n");
			out.write("\t\t\t\t\t\t\t");

			// java代码
			ArticleSerivce as = new ArticleSerivceImpl();

			// 调用其方�?
			List<Article> list = as.getArticles();

			for (Article article : list) {

				out.write("\r\n");
				out.write("\t\t\t\t\t\t\t\r\n");
				out.write("\t\t\t\t\t\t\t<tr>\r\n");
				out.write("\t\t\t\t\t\t\t\t<td>");
				out.print(article.getArticleId());
				out.write("</td>\r\n");
				out.write("\t\t\t\t\t\t\t\t<td>");
				out.print(article.getArticleTitle());
				out.write("</td>\r\n");
				out.write("\t\t\t\t\t\t\t\t<td>");
				out.print(article.getArticleContent());
				out.write("</td>\r\n");
				out.write("\t\t\t\t\t\t\t\t<td>");
				out.print(article.getArticleAuthor());
				out.write("</td>\r\n");
				out.write("\t\t\t\t\t\t\t\t<td>");
				out.print(article.getArticleDate());
				out.write("</td>\r\n");
				out.write("\t\t\t\t\t\t\t\t<td><a href=\"#\">修改</a><a href=\"#\">删除</a></td>\r\n");
				out.write("\t\t\t\t\t\t\t</tr>\r\n");
				out.write("\t\t\t\t\t\t\t\r\n");
				out.write("\t\t\t\t\t\t\t");

			}

			out.write("\r\n");
			out.write("\r\n");
			out.write("\t\t\t\t\t\t\t\r\n");
			out.write("\r\n");
			out.write("\r\n");
			out.write("\t\t\t\t\t\t</tbody>\r\n");
			out.write("\t\t\t\t\t</table>\r\n");
			out.write("\r\n");
			out.write("\t\t\t\t\t<!--\r\n");
			out.write("            \t作�?�：offline\r\n");
			out.write("            \t时间�?2018-05-10\r\n");
			out.write("            \t描述：分页的导航\r\n");
			out.write("            -->\r\n");
			out.write("\r\n");
			out.write("\t\t\t\t\t<div class=\"col-md-12 column text-center\">\r\n");
			out.write("\t\t\t\t\t\t<ul class=\"pagination\">\r\n");
			out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Prev</a></li>\r\n");
			out.write("\t\t\t\t\t\t\t<li><a href=\"#\">1</a></li>\r\n");
			out.write("\t\t\t\t\t\t\t<li><a href=\"#\">2</a></li>\r\n");
			out.write("\t\t\t\t\t\t\t<li><a href=\"#\">3</a></li>\r\n");
			out.write("\t\t\t\t\t\t\t<li><a href=\"#\">4</a></li>\r\n");
			out.write("\t\t\t\t\t\t\t<li><a href=\"#\">5</a></li>\r\n");
			out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Next</a></li>\r\n");
			out.write("\t\t\t\t\t\t</ul>\r\n");
			out.write("\t\t\t\t\t</div>\r\n");
			out.write("\t\t\t\t</div>\r\n");
			out.write("\t\t\t</div>\r\n");
			out.write("\t\t</div>\r\n");
			out.write("\t</div>\r\n");
			out.write("\r\n");
			out.write("\t<!-- Bootstrap core JavaScript\r\n");
			out.write("    ================================================== -->\r\n");
			out.write("\t<!-- Placed at the end of the document so the pages load faster -->\r\n");
			out.write("\t<script\r\n");
			out.write("\t\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
			out.write("\t<script>\r\n");
			out.write("\t\twindow.jQuery\r\n");
			out.write("\t\t\t\t|| document\r\n");
			out.write("\t\t\t\t\t\t.write('<script src=\"../../assets/js/vendor/jquery.min.js\"><\\/script>')\r\n");
			out.write("\t</script>\r\n");
			out.write("\t<script src=\"../../dist/js/bootstrap.min.js\"></script>\r\n");
			out.write("\t<!-- Just to make our placeholder images work. Don't actually copy the next line! -->\r\n");
			out.write("\t<script src=\"../../assets/js/vendor/holder.min.js\"></script>\r\n");
			out.write("\t<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->\r\n");
			out.write("\t<script src=\"../../assets/js/ie10-viewport-bug-workaround.js\"></script>\r\n");
			out.write("</body>\r\n");
			out.write("\r\n");
			out.write("</html>");
		} catch (java.lang.Throwable t) {
			if (!(t instanceof javax.servlet.jsp.SkipPageException)) {
				out = _jspx_out;
				if (out != null && out.getBufferSize() != 0)
					try {
						if (response.isCommitted()) {
							out.flush();
						} else {
							out.clearBuffer();
						}
					} catch (java.io.IOException e) {
					}
				if (_jspx_page_context != null)
					_jspx_page_context.handlePageException(t);
				else
					throw new ServletException(t);
			}
		} finally {
			_jspxFactory.releasePageContext(_jspx_page_context);
		}
	}
}
*/